name: Build and Push to Aliyun

on:
  push:
    branches:
      - main  # 或者你使用的其他分支名

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Aliyun Container Registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.REGISTRY_URL }}/infisical:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.REGISTRY_URL }}/infisical:latest
