name: Build and Push to Aliyun

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to ACR
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" \
            | docker login ${{ secrets.ALIYUN_REGISTRY }} \
              -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ALIYUN_REGISTRY }}/infisical:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.ALIYUN_REGISTRY }}/infisical:latest
